### ISSUE TITLE
Add links to Github (and maybe Twitter) profile.

### ISSUE THREAD

**Issue by michael-simons** [docToolchain/aoc-2019#121]
Please add links to at least the Github profiles and if somewhat possible, to twitter. The later could be done via adding a handle as asciidoc tag to one arbitrary readme of that user.

**Comment by rdmueller** [comment]
can you please check this:
https://aoc-2019.netlify.com/generated/coder/michael-simons/generateddays

there is now a basic profile and a folder `/profiles` where you can update your profile. The leaderboard now also links to the Developer page which starts with the profile...

If you like it, you can close this ticket and tweet about it.
Otherwise, feedback ist welcome!

**Comment by michael-simons** [comment]
Great solution! Thank you!
